[tool.ruff]
line-length = 100
lint.select = [
    "A",
    "ANN",
    "ARG",
    "B",
    "C4",
    "D",
    "E",
    "F",
    "ICN",
    "ISC",
    "N",
    "PD",
    "PGH",
    "PLR",
    "PLW",
    "PIE",
    "PT",
    "Q",
    "RET",
    "RUF",
    "S",
    "SIM",
    "TID",
    "UP",
    "W",
    "YTT",
]
lint.ignore = [
    "A001",
    "A003",
    "ANN101",
    "ANN102",
    "ANN401",
    "B008",
    "B017",
    "B019",
    "C405",
    "D103",
    "D107",
    "D200",
    "D202",
    "D203",
    "D205",
    "D212",
    "D400",
    "D401",
    "D403",
    "D404",
    "D415",
    "E501",
    "N818",
    "PGH003",
    "PGH004",
    "PLR2004",
    "PT011",
    "PT012",
    "RUF013",
    "S101",
    "S105",
    "S108",
    "S311",
    "W605",
]
target-version = "py38"
exclude = [
    ".direnv",
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "__pypackages__",
]
