name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: build and publish
        run: poetry publish --build -n -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASSWORD }}
