name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: jpetrucciani/ruff-check@main
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: jpetrucciani/black-check@master
        with:
          path: 'bucketstore.py'
  tests:
    runs-on: ubuntu-latest
    needs: [ruff, black]
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12']
    name: python ${{ matrix.python-version }} tests
    steps:
      - uses: actions/checkout@v4.1.7
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'poetry'
      - run: poetry install
      - run: poetry run pytest ./tests -s --cov . --cov-report html --cov-report term --cov-report xml:coverage.xml --junitxml=report.xml
