name: test

on: [push, pull_request]

jobs:
  prospector:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: jpetrucciani/prospector-check@master
  mypy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: jpetrucciani/mypy-check@master
        with:
          path: 'bucketstore.py'
  black:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: jpetrucciani/black-check@master
        with:
          path: 'bucketstore.py'
